apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: control-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: control-service
    spec:
      containers:
      - name: control
        image: europe-north1-docker.pkg.dev/dse24-group-09/dse-repo/control:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        envFrom:
          - secretRef:
              name: mongodb-control-control-user # Created by mongodb
          - secretRef:
              name: rabbitmq-custom-user
        env:
          - name: BEACHCOMB_SERVICE_URL
            value: beachcomb-service.dse.svc.cluster.local