apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: event-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: event-service
    spec:
      containers:
      - name: event
        image: europe-north1-docker.pkg.dev/dse24-group-09/dse-repo/event:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4449
        envFrom:
          - secretRef:
              name: mongodb-event-event-user # Created by mongodb
          - secretRef:
              name: rabbitmq-default-user # Created by rabbitmq
