apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: event-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082