---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: web-mapping
  namespace: {{ .Values.namespace }}
spec:
  hostname: "*"
  prefix: /
  service: web-service.{{ .Values.namespace }}
  rewrite: /
