apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: web-service
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 80