apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory-service
    spec:
      containers:
      - name: inventory
        image: inventory:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: inventory-mongodb-inventory-inventory-user
