apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory-service
    spec:
      containers:
      - name: inventory
        image: europe-north1-docker.pkg.dev/dse24-group-09/dse-repo/inventory:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4444
        envFrom:
          - secretRef:
              name: mongodb-inventory-inventory-user # Created by mongodb
          - secretRef:
              name: rabbitmq-custom-user
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: testdata
